### ISSUE TITLE
Error Returned for Specific W2V Configuration

### ISSUE THREAD

**Issue by dave-lab41** [Lab41/pythia#125]
Word2vec functionality returns an error for logistic regression and xgboost for a certain combination of config variables.

config file:
{ "directory" : "data/stackexchange/english", "VOCAB_SIZE" : 50000, "STEM" : false, "RESAMPLING" : true, "OVERSAMPLING" : false, "REPLACEMENT" : false, "SAVE_RESULTS" : true, "USE_CACHE" : true, "W2V_AVG" : true, "W2V_APPEND" : true, "XGB" : true }

log_reg error:
ValueError: setting an array element with a sequence.

xgboost error:
TypeError: can not initialize DMatrix from list

**Comment by pcallier** [comment]
so you get the TypeError with this config and the ValueError when `"XGB": true`  is `"LOG_REG": true`?

**Comment by pcallier** [comment]
related to problems with how W2V_AVG handles missing values when a sentence is all out-of-vocab tokens ht/ @dave-lab41
