### ISSUE TITLE
Stemming + word2vec etc

### ISSUE THREAD

**Issue by pcallier** [Lab41/pythia#132]
When stemming is requested it appears that all vocabularies and a lot of code using xml_normalize are filled with stemmed entries, even for methods like word2vec which might not get along well with stemming. Is there a way to support stemming in (for instance) BoW but keep unstemmed vocabs for word2vec and other such algorithms?

**Comment by dave-lab41** [comment]
Short version: While xml_normalize includes the option for stemming, the stemming option is not used in the pipeline when word2vec is trained or evaluated. 

Long version: It's true that xml_normalize has the option for stemming

`def xml_normalize(raw_text, stem=False, **kwargs ):`

`if stem: lower_case = porter_stem(lower_case)`

but it appears that when Word2Vec calls xml_normalize during training, it doesn't pass in a stem value. 

`sentences = tokenize.punkt_sentences(xml_normalize(entry['body_text']))`

Given that stem is set to False by default, Word2Vec should be trained without stemming.

When Word2Vec is evaluating the training/testing data, it calls 

`get_first_and_last_sentence(doc)`

which also uses xml_normalize without passing a stem setting:

```
first = normalize.xml_normalize(sentences[0])
last = normalize.xml_normalize(sentences[-1])
```

**Comment by pcallier** [comment]
Closing this as it seems the behavior is as expected.
