### ISSUE TITLE
Single algorithm per run

### ISSUE THREAD

**Issue by pcallier** [Lab41/pythia#73]
Training/evaluating multiple algorithms in one run saves time on preprocessing, but make some other logic messy (such as if an algorithm does its own preprocessing, e.g. DMN, and doesn't need some of the obligatory precompute), and it muddies the links between specific hyperparameter settings and specific results (e.g., SVM hyperparameters may look like they are changing alognside metrics from log reg). It also makes it hard to validate random state (see #42) since different combinations of algorithms may involve different sequences of random operations.  Recommend enforcing that only one algorithm used per run; doing some kind of data caching (see #72) only when necessary.

**Comment by dave-lab41** [comment]
Single algorithm per run enforced as of pull request #91. Caching of intermediate products and models remains an open issue.
