### ISSUE TITLE
Move VOCAB size setting to parameter dictionary

### ISSUE THREAD

**Issue by dave-lab41** [Lab41/pythia#80]
VOCAB size is currently duplicated in the BOW and LDA dictionaries. Moving it to the parameter dictionary will standardize vocabulary size across featurizers.

**Comment by pcallier** [comment]
It is possible that someone would want different-sized dictionaries for these two techniques but I think the logic for vocab generation doesn't take this into account either. I'm okay merging both into one VOCAB param since it is more in keeping with our only-do-things-once spirit.
